@startuml

'swimlane Arzt

'swimlane Arzt und Patient
'swimlane Patient


|Arzt|
start
:Ziel definieren;
|#AntiqueWhite|Arzt und Patient|
repeat
    :Mit Patienten besprechen\nund falls nötig bearbeiten;
    :Termin für Abschluss des Zieles \nmit dem Patienten ausmachen;
    |Patient|
    :Versucht das Ziel zu erfüllen;
    |#AntiqueWhite|Arzt und Patient|
    :Ziel auswerten;

repeat while (Ziel erfüllt) -> Nein
    ->Ja;
    |Arzt|
    |#AntiqueWhite|Arzt und Patient|



fork
    |Arzt|
	:Folgeziel definieren;
	note left
      Wieder am Anfang
      des Prozesses
    end note
  fork again
    |#AntiqueWhite|Arzt und Patient|
	:Ziel abschliessen;
  end fork

|Arzt|
stop

@enduml