@startuml
actor Arzt

rectangle "Patienten Management System" as pms{
    (Rückfragen erstellen) as quest
    (Fragen einsehen) as showQ
    (Fragen beantworten) as respond
    (Antwort eintragen) as answer

}

Arzt -left-> quest
Arzt -left-> showQ
Arzt -left-> respond
Arzt -left-> answer


@enduml