@startuml
actor Arzt
rectangle System

rectangle "Patienten Management System" as pms {
    (Analoger Report einscannen) as scan
    (Geschriebenes in digitalen Report umwandeln) as convert
    (Digitaler Report überarbeiten) as edit
    (Digitaler Report speichern) as save

    scan <.down. convert: <includes>
    convert <.down. edit: <includes>
    edit <.down. save: <includes>
}

Arzt -right-> scan
Arzt -right-> edit
Arzt -right-> save

System -left-> convert


@enduml