@startuml

actor DoctorX

participant Objective

activate DoctorX

DoctorX -> Objective : create(objective,date)
activate Objective
Objective --> DoctorX

DoctorX -> Objective : updateDueDate(objective,date)
Objective --> DoctorX

DoctorX -> Objective : finish(objective)
Objective --> DoctorX

DoctorX -> Objective : evaluate/show()
Objective --> DoctorX

deactivate Objective
deactivate DoctorX
@enduml