@startuml




package Model {
    interface Buildable {
      +build(): T
    }
    interface Queriable {
      +getById(): T
      +getBy(filters: Array): T
      +getAll(): list<t>
    }



    class MessageBuilder{
        + createAndNotify(): boolean
    }
}

' TODO
'Report "1" *-- "*" Message
'Report "*" -left-o "*" Doctor
'Patient "1" *- "*" Objective
'Report "*" -right* "1" Dossier
'Dossier "1" --* "1" Patient
'Objective "*" - "1" Doctor
'Doctor "1" - "*" Patient
'Message "*" -left- "1" Doctor
'UnitOfWork "1" -left- "*" ModelRepository


'View "1" -- "1" MainPresenter
'MainPresenter <|-- HomePresenter
'MainPresenter <|-- DossierPresenter
'MainPresenter <|-- ReportPresenter
'ReportPresenter -up- MessageBuilder
'ReportPresenter -up- MessageQuerier
'HomePresenter -up- DoctorQuerier
'HomePresenter -up- PatientQuerier
'ReportPresenter -up- ReportQuerier
'DossierPresenter -up- DossierQuerier

'DossierQuerier "1" -up- "1" UnitOfWork
'DoctorQuerier "1" -- "1" UnitOfWork
'PatientQuerier "1" -- "1" UnitOfWork
'ReportQuerier "1" -- "1" UnitOfWork
'MessageQuerier "1" -- "1" UnitOfWork
'MessageBuilder "1" -- "1" UnitOfWork

note top of Model: Every model class has a setter and a getter for all attribute

@enduml